language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - make requirements-dev
script:
  - PYTEST_ARGS='--cov=dmcontent --cov-report=term-missing' make test
after_success:
  - coveralls
notifications:
  email: false
