language: python
python:
  - "3.6"
install:
  - pip install -r requirements-dev.txt
script:
  - PYTEST_ARGS='--cov=dmcontent --cov-report=term-missing' make test
after_success:
  - coveralls
notifications:
  email: false
