language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements_for_test.txt
script:
  - PYTEST_ARGS='--cov=dmcontent --cov-report=term-missing' make test
after_success:
  - coveralls
notifications:
  email: false
